name: gosmart
description: GoSmart — Universal transport card with AI for smart cities.
version: 1.0.0+1
publish_to: none

environment:
  sdk: ">=3.2.0 <4.0.0"

dependencies:
  flutter:
    sdk: flutter

  # UI — fuentes via red (no requiere archivos locales)
  google_fonts: ^6.2.1

  # QR
  qr_flutter: ^4.1.0

  # Utilidades básicas
  intl: ^0.19.0

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^3.0.0

flutter:
  uses-material-design: true
  generate: false

  assets:
    - assets/icons/
    - assets/images/
    - assets/animations/
